image: "quay.io/coreos/etcd:v3.3.4"
cluster_token: "cluster0"
cloud_provider: "baremetal"
members:
  - name: "etcd1"
    advertise_client_urls: "http://172.17.8.51:2379"
    initial_advertise_peer_urls: "http://172.17.8.51:2380"
    data_volume_id: "w/e"
    wal_volume_id: "w/e"
  - name: "etcd2"
    advertise_client_urls: "http://172.17.8.52:2379"
    initial_advertise_peer_urls: "http://172.17.8.52:2380"
    data_volume_id: "w/e"
    wal_volume_id: "w/e"
  - name: "etcd3"
    advertise_client_urls: "http://172.17.8.53:2379"
    initial_advertise_peer_urls: "http://172.17.8.53:2380"
    data_volume_id: "w/e"
    wal_volume_id: "w/e"
